substitutions:
  _DB_USER: projects/292927587123/secrets/db_user/versions/latest
  _DB_PASS: projects/292927587123/secrets/db_pass/versions/latest
  _DB_PORT: projects/292927587123/secrets/db_port/versions/latest
  _DB_NAME: projects/292927587123/secrets/db_name/versions/latest
  _SECRET_KEY: projects/292927587123/secrets/secret_key/versions/latest
  _ALGORITHM: projects/292927587123/secrets/algorithm/versions/latest
  _ACCESS_TOKEN_EXPIRE_MINUTES: projects/292927587123/secrets/access_token_expire_minutes/versions/latest
  _ADMIN_USERNAME: projects/292927587123/secrets/admin_username/versions/latest
  _ADMIN_PASS: projects/292927587123/secrets/admin_pass/versions/latest
  _ADMIN_EMAIL: projects/292927587123/secrets/admin_email/versions/latest
  _DB_CLOUD: projects/292927587123/secrets/db_cloud/versions/latest

steps:
  # Build the container image for test
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'test_runner', '.']
    env:
      - "DOCKER_BUILDKIT=1"

  # test
  - name: 'test_runner'
    env:
      - 'DB_USER=$_DB_USER'
      - 'DB_PASS=$_DB_PASS'
      - 'DB_PORT=$_DB_PORT'
      - 'DB_NAME=$_DB_NAME'
      - 'SECRET_KEY=$_SECRET_KEY'
      - 'ALGORITHM=$_ALGORITHM'
      - 'ACCESS_TOKEN_EXPIRE_MINUTES=$_ACCESS_TOKEN_EXPIRE_MINUTES'
      - 'ADMIN_USERNAME=$_ADMIN_USERNAME'
      - 'ADMIN_PASS=$_ADMIN_PASS'
      - 'ADMIN_EMAIL=$_ADMIN_EMAIL'
      - 'DB_CLOUD=$_DB_CLOUD'

    args:
      - 'python'
      - '-m'
      - 'pytest'


  # Install Poetry within the Docker container
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pip install poetry && poetry install'

  # Install dependencies using Poetry
  - name: python
    entrypoint: poetry
    args: ["install", "--no-interaction", "--no-ansi"]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/percentpassed/percent/percent-app:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/percentpassed/percent/percent-app:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'percent-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/percentpassed/percent/percent-app:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--update-secrets'
      - 'DB_USER=db_user:latest,DB_PASS=db_pass:latest,DB_PORT=db_port:latest,DB_NAME=db_name:latest,SECRET_KEY=secret_key:latest,ALGORITHM=algorithm:latest,ACCESS_TOKEN_EXPIRE_MINUTES=access_token_expire_minutes:latest,ADMIN_USERNAME=admin_username:latest,ADMIN_PASS=admin_pass:latest,ADMIN_EMAIL=admin_email:latest,DB_CLOUD=db_cloud:latest'
      - '--add-cloudsql-instances'
      - 'percentpassed:us-central1:percent'
      - '--port'
      - '8000'
