"""Add country code

Revision ID: 9749b607229c
Revises: cd7301fffe4a
Create Date: 2023-08-16 16:07:25.640944

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "9749b607229c"
down_revision = "cd7301fffe4a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "residence", sa.Column("country_code", sa.String(length=5), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("residence", "country_code")
    # ### end Alembic commands ###
