"""Init

Revision ID: b6190175b140
Revises: 
Create Date: 2023-06-30 19:39:27.117501

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b6190175b140"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
