"""add present option for end_date

Revision ID: cd7301fffe4a
Revises: de2ad612ceb3
Create Date: 2023-08-09 13:20:06.465902

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "cd7301fffe4a"
down_revision = "de2ad612ceb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("residence", "end_date", type_=sa.String(length=10))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("residence", "end_date", type_=sa.Date())
    # ### end Alembic commands ###
