"""add city

Revision ID: de2ad612ceb3
Revises: a9c36e59e74a
Create Date: 2023-08-05 11:24:06.033841

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "de2ad612ceb3"
down_revision = "a9c36e59e74a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("residence", sa.Column("city", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("residence", "city")
    # ### end Alembic commands ###
